-- MLB Walkup Songs - Supabase Schema
-- Run this in the Supabase SQL Editor

-- ============================================
-- TABLE: mlb_walk_up_songs
-- Main table for walkup song records
-- Compatible with scraper.py change tracking
-- ============================================
CREATE TABLE IF NOT EXISTS mlb_walk_up_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team VARCHAR(50) NOT NULL,
    player VARCHAR(255) NOT NULL,
    song_name VARCHAR(500) NOT NULL,
    song_artist VARCHAR(500),
    spotify_uri VARCHAR(255),
    explicit BOOLEAN,
    first_seen_date DATE NOT NULL,
    last_updated_date DATE NOT NULL,
    is_current BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Prevent duplicate song entries per player
    UNIQUE(team, player, song_name)
);

-- Indexes for common queries (matching scraper.py expectations)
CREATE INDEX IF NOT EXISTS idx_player_current ON mlb_walk_up_songs(team, player, is_current);
CREATE INDEX IF NOT EXISTS idx_first_seen ON mlb_walk_up_songs(first_seen_date);
CREATE INDEX IF NOT EXISTS idx_last_updated ON mlb_walk_up_songs(last_updated_date);

-- ============================================
-- TABLE: batting_stats
-- Daily batting statistics per player
-- ============================================
CREATE TABLE IF NOT EXISTS batting_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL,
    player_id INTEGER,
    game_date DATE NOT NULL,
    year INTEGER NOT NULL,
    team TEXT,
    game_number INTEGER,
    plate_appearances INTEGER DEFAULT 0,
    at_bats INTEGER DEFAULT 0,
    hits INTEGER DEFAULT 0,
    singles INTEGER DEFAULT 0,
    doubles INTEGER DEFAULT 0,
    triples INTEGER DEFAULT 0,
    home_runs INTEGER DEFAULT 0,
    walks INTEGER DEFAULT 0,
    strikeouts INTEGER DEFAULT 0,
    hbp INTEGER DEFAULT 0,
    sac_fly INTEGER DEFAULT 0,
    batting_avg NUMERIC(4,3),
    obp NUMERIC(4,3),
    slg NUMERIC(4,3),
    ops NUMERIC(4,3),
    total_bases INTEGER DEFAULT 0,
    data_source TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Prevent duplicate entries for same player/game
    UNIQUE(player_name, game_date, game_number)
);

-- Indexes for batting stats queries
CREATE INDEX IF NOT EXISTS idx_batting_stats_player ON batting_stats(player_name);
CREATE INDEX IF NOT EXISTS idx_batting_stats_date ON batting_stats(game_date);
CREATE INDEX IF NOT EXISTS idx_batting_stats_team ON batting_stats(team);
CREATE INDEX IF NOT EXISTS idx_batting_stats_player_date ON batting_stats(player_name, game_date);

-- ============================================
-- TABLE: song_changes (for causal analysis)
-- Tracks when players change their walkup songs
-- ============================================
CREATE TABLE IF NOT EXISTS song_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player TEXT NOT NULL,
    team TEXT NOT NULL,
    old_song_name TEXT,
    old_song_artist TEXT,
    new_song_name TEXT NOT NULL,
    new_song_artist TEXT,
    change_date DATE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_song_changes_player ON song_changes(player);
CREATE INDEX IF NOT EXISTS idx_song_changes_date ON song_changes(change_date);

-- ============================================
-- FUNCTION: Auto-update updated_at timestamp
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- Trigger for mlb_walk_up_songs
DROP TRIGGER IF EXISTS update_mlb_walk_up_songs_updated_at ON mlb_walk_up_songs;
CREATE TRIGGER update_mlb_walk_up_songs_updated_at
    BEFORE UPDATE ON mlb_walk_up_songs
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- ROW LEVEL SECURITY (RLS)
-- Enable for Supabase Auth integration
-- ============================================

-- Enable RLS on all tables
ALTER TABLE mlb_walk_up_songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE batting_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE song_changes ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for your app)
CREATE POLICY "Allow public read access on walkup songs"
    ON mlb_walk_up_songs FOR SELECT
    USING (true);

CREATE POLICY "Allow public read access on batting stats"
    ON batting_stats FOR SELECT
    USING (true);

CREATE POLICY "Allow public read access on song changes"
    ON song_changes FOR SELECT
    USING (true);

-- ============================================
-- SERVICE ROLE POLICIES (for backend/scraper)
-- Only the scraper (using service_role key) can write data
-- Do NOT use service_role key in client-side code
-- ============================================
CREATE POLICY "Service role full access on walkup songs"
    ON mlb_walk_up_songs FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role full access on batting stats"
    ON batting_stats FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service role full access on song changes"
    ON song_changes FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- ============================================
-- VIEWS for common queries
-- ============================================

-- Current walkup songs (using is_current flag)
-- security_invoker ensures RLS policies are respected
CREATE OR REPLACE VIEW current_walkup_songs
WITH (security_invoker = true) AS
SELECT
    id,
    team,
    player,
    song_name,
    song_artist,
    first_seen_date,
    last_updated_date,
    spotify_uri,
    explicit,
    updated_at
FROM mlb_walk_up_songs
WHERE is_current = TRUE;

-- Player stats summary
-- security_invoker ensures RLS policies are respected
-- Uses weighted averages for accurate stats (not avg of avgs)
CREATE OR REPLACE VIEW player_stats_summary
WITH (security_invoker = true) AS
SELECT
    player_name,
    team,
    year,
    COUNT(*) as games_played,
    SUM(plate_appearances) as total_pa,
    SUM(at_bats) as total_ab,
    SUM(hits) as total_hits,
    SUM(home_runs) as total_hr,
    -- Weighted batting average: total hits / total at-bats
    CASE
        WHEN SUM(at_bats) > 0
        THEN ROUND((SUM(hits)::numeric / SUM(at_bats)), 3)
        ELSE NULL
    END as avg_batting_avg,
    -- Weighted OPS: weighted by plate appearances
    CASE
        WHEN SUM(plate_appearances) > 0
        THEN ROUND((SUM(ops * plate_appearances) / SUM(plate_appearances)), 3)
        ELSE NULL
    END as avg_ops
FROM batting_stats
GROUP BY player_name, team, year;
